export type SidebarDocItem = Readonly<{
  type: 'doc'
  id: string
}>

export type SidebarCategoryLink = Readonly<
  | {
      type: 'doc'
      id: string
    }
  | {
      type: 'generated-index'
    }
>

export type SidebarCategoryItem = Readonly<{
  type: 'category'
  items: readonly SidebarItem[]
  link?: SidebarCategoryLink
}>

export type SidebarNonDocItem = Readonly<{
  type: 'autogenerated' | 'html' | 'link' | 'ref'
}>

export type SidebarItem = SidebarDocItem | SidebarCategoryItem | SidebarNonDocItem | string

export function extractSidebarDocIds(items: readonly SidebarItem[]): Set<string> {
  const ids = new Set<string>()

  for (const item of items) {
    if (typeof item === 'string') {
      ids.add(item)
    } else if (item.type === 'doc') {
      ids.add(item.id)
    } else if (item.type === 'category') {
      if (item.link?.type === 'doc') {
        ids.add(item.link.id)
      }
      for (const id of extractSidebarDocIds(item.items)) {
        ids.add(id)
      }
    }
  }

  return ids
}
